/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas.paneles;

import com.linuxense.javadbf.DBFException;
import com.linuxense.javadbf.DBFField;
import com.linuxense.javadbf.DBFReader;
import com.migracion.Importacion;
import com.utilidades.Fechas;
import com.utilidades.PersonalFileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author misanchez
 */
public class V_Importacion extends javax.swing.JDialog {

    private String[] nombreCols;
    private Class[] tipoDeDatos;

    /**
     * Creates new form V_Importacion
     */
    public V_Importacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        fileChooser.setFileFilter(new PersonalFileFilter("DBF", "Base de datos de FOX"));
        ubicacionField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comprasRadioButton = new javax.swing.JRadioButton();
        ventasCFRadioButton = new javax.swing.JRadioButton();
        ventasCRadioButton = new javax.swing.JRadioButton();
        clientesRadioButton = new javax.swing.JRadioButton();
        proveedoresRadioButton = new javax.swing.JRadioButton();
        mesMonthChooser = new com.toedter.calendar.JMonthChooser();
        anhoYearChooser = new com.toedter.calendar.JYearChooser();
        ubicacionField = new com.controles.JXTextFiled();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosTable = new javax.swing.JTable();
        importarButton = new javax.swing.JButton();
        otraCargaButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("1. Tipo de importación:");

        jLabel2.setText("2. Seleccione el archivo:");

        jLabel3.setText("3. Vista de datos:");

        jLabel4.setText("2. Periodo de importación:");

        jLabel5.setText("MES");

        jLabel6.setText("AÑO");

        buttonGroup.add(comprasRadioButton);
        comprasRadioButton.setSelected(true);
        comprasRadioButton.setText("Compras");

        buttonGroup.add(ventasCFRadioButton);
        ventasCFRadioButton.setText("Ventas al Consumidor Final");

        buttonGroup.add(ventasCRadioButton);
        ventasCRadioButton.setText("Ventas al Contribuyente");

        buttonGroup.add(clientesRadioButton);
        clientesRadioButton.setText("Clientes");

        buttonGroup.add(proveedoresRadioButton);
        proveedoresRadioButton.setText("Proveedores");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        datosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(datosTable);

        importarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/aceptar.png"))); // NOI18N
        importarButton.setText("Importar");
        importarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarButtonActionPerformed(evt);
            }
        });

        otraCargaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/actualizar.png"))); // NOI18N
        otraCargaButton.setText("Otra importación");
        otraCargaButton.setEnabled(false);
        otraCargaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otraCargaButtonActionPerformed(evt);
            }
        });

        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/salir.png"))); // NOI18N
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubicacionField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(importarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otraCargaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anhoYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comprasRadioButton)
                                    .addComponent(clientesRadioButton))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proveedoresRadioButton)
                                    .addComponent(ventasCFRadioButton))))
                        .addGap(35, 35, 35)
                        .addComponent(ventasCRadioButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comprasRadioButton)
                    .addComponent(ventasCFRadioButton)
                    .addComponent(ventasCRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesRadioButton)
                    .addComponent(proveedoresRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(mesMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anhoYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ubicacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirButton)
                    .addComponent(otraCargaButton)
                    .addComponent(importarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            InputStream is = null;
            try {
                is = new FileInputStream(fileChooser.getSelectedFile());
                ubicacionField.setText(fileChooser.getSelectedFile().getPath());
                cargarDatos(is);
            } catch (DBFException ex) {
                Logger.getLogger(V_Importacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(V_Importacion.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    is.close();
                } catch (IOException ex) {
                    Logger.getLogger(V_Importacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void importarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarButtonActionPerformed
        importar();
        activarBotones(false);
    }//GEN-LAST:event_importarButtonActionPerformed

    private void otraCargaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otraCargaButtonActionPerformed
        datosTable.setModel(new DefaultTableModel());
        ubicacionField.setText("");
        activarBotones(true);
    }//GEN-LAST:event_otraCargaButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                V_Importacion dialog = new V_Importacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anhoYearChooser;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton clientesRadioButton;
    private javax.swing.JRadioButton comprasRadioButton;
    private javax.swing.JTable datosTable;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton importarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser mesMonthChooser;
    private javax.swing.JButton otraCargaButton;
    private javax.swing.JRadioButton proveedoresRadioButton;
    private javax.swing.JButton salirButton;
    private com.controles.JXTextFiled ubicacionField;
    private javax.swing.JRadioButton ventasCFRadioButton;
    private javax.swing.JRadioButton ventasCRadioButton;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(InputStream is) throws DBFException {
        try {
            DBFReader dbfIn = new DBFReader(is);

            nombreCols = new String[dbfIn.getFieldCount()];
            tipoDeDatos = new Class[dbfIn.getFieldCount()];

            for (int i = 0; i < dbfIn.getFieldCount(); i++) {
                DBFField field = dbfIn.getField(i);
                nombreCols[i] = field.getName();
                tipoDeDatos[i] = getTipoDato(field);
            }

            datosTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    nombreCols) {

                Class[] types = tipoDeDatos;

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }
            });
            
            Object[] rowObjects;

            while ((rowObjects = dbfIn.nextRecord()) != null) {
                ((DefaultTableModel)datosTable.getModel()).addRow(rowObjects);
            }
            
            is.close();
        } catch (IOException ex) {
            Logger.getLogger(V_Importacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Class getTipoDato(DBFField field) {
        Class clase = null;

        switch (field.getDataType()) {
            case DBFField.FIELD_TYPE_C:
                clase = String.class;
                break;
            case DBFField.FIELD_TYPE_D:
                clase = Date.class;
                break;
            case DBFField.FIELD_TYPE_F:
            case DBFField.FIELD_TYPE_N:
                clase = Double.class;
                break;
            case DBFField.FIELD_TYPE_L:
                clase = Boolean.class;
                break;
        }
        return clase;
    }
    
    private void activarBotones(boolean bandera){
        importarButton.setEnabled(bandera);
        otraCargaButton.setEnabled(!bandera);
        
    }

    private void importar() {        
        if(!ubicacionField.getText().isEmpty()){
            if(comprasRadioButton.isSelected()){
                Importacion.compras(ubicacionField.getText(), Fechas.getNumeroMes(String.valueOf(mesMonthChooser.getMonth()+1))+anhoYearChooser.getYear());
            }else if(ventasCFRadioButton.isSelected()){
                Importacion.ventaConsumidorFinal(ubicacionField.getText(), Fechas.getNumeroMes(String.valueOf(mesMonthChooser.getMonth()+1))+anhoYearChooser.getYear());
            }else if(ventasCRadioButton.isSelected()){
                Importacion.ventaContribuyente(ubicacionField.getText(), Fechas.getNumeroMes(String.valueOf(mesMonthChooser.getMonth()+1))+anhoYearChooser.getYear());
            }else if(proveedoresRadioButton.isSelected()){
                Importacion.organizacion(ubicacionField.getText(), 2);
            }else if(clientesRadioButton.isSelected()){
                Importacion.organizacion(ubicacionField.getText(), 1);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe de seleccionar un archivo!", "Error", JOptionPane.ERROR_MESSAGE);
            jButton1.requestFocus();
        }
    }
}
