/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas.paneles;

import com.controles.dibujadorDeColumna.NumerosRenderer;
import com.controles.editorDeColumna.DefaultCellEdit;
import com.controles.editorDeColumna.NumeroEdit;
import com.controles.editorDeColumna.OrganizacionEdit;
import com.controles.editorDeColumna.SucursalEdit;
import com.entidades.Documento;
import com.entidades.Organizacion;
import com.entidades.Sucursal;
import com.entidades.VentaContribuyente;
import com.servicio.ServDocumento;
import com.servicio.ServOrganizacion;
import com.servicio.ServSucursal;
import com.servicio.ServVtaContribuyente;
import com.utilidades.AccesoAVtaPadre;
import com.utilidades.AdministradorEntidades;
import com.utilidades.Fechas;
import com.utilidades.OperacionMatematica;
import com.utilidades.OperacionesGUI;
import com.vistas.VtnaSuma;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author misanchez
 */
public class V_LibroVtaContribuyente extends JPanel implements Persistencia {

    public V_LibroVtaContribuyente() {
        initComponents();
        if (!Beans.isDesignTime()) {
            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
        }

        OperacionesGUI.setRender(masterTable);

        masterTable.setCellEditor(1, new NumeroEdit(false, JTextField.LEFT));
        //masterTable.setCellEditor(2, new DocumentoEdit(true));
        masterTable.setCellEditor(2, new DefaultCellEdit(true));
        masterTable.setCellEditor(3, new NumeroEdit(false, JTextField.RIGHT));
        masterTable.setCellEditor(4, new NumeroEdit(false, JTextField.RIGHT));
        masterTable.setCellEditor(5, new OrganizacionEdit(1));

        masterTable.setCellEditor(9, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(10, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(11, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(12, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(13, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(14, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(15, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(16, new NumeroEdit(true, JTextField.RIGHT));
        masterTable.setCellEditor(17, new SucursalEdit(false));


        masterTable.setCellRenderer(9, new NumerosRenderer());
        masterTable.setCellRenderer(10, new NumerosRenderer());
        masterTable.setCellRenderer(11, new NumerosRenderer());
        masterTable.setCellRenderer(12, new NumerosRenderer());
        masterTable.setCellRenderer(13, new NumerosRenderer());
        masterTable.setCellRenderer(14, new NumerosRenderer());
        masterTable.setCellRenderer(15, new NumerosRenderer());
        masterTable.setCellRenderer(16, new NumerosRenderer());

        masterTable.setColsSumar("16=9+10+11");
        masterTable.setColsMultiplicar("11=10");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = AdministradorEntidades.getInstance().getEM();
        lstVtaContribuyente = ServVtaContribuyente.getListado();
        lstDocumento = ServDocumento.getListadoVentas();
        lstSucursal = ServSucursal.getListado();
        codigoOrgField = new com.controles.JXTextFiled();
        diaLabel = new javax.swing.JLabel();
        idDocLabel = new javax.swing.JLabel();
        NCompVentaLabel = new javax.swing.JLabel();
        NFormLabel = new javax.swing.JLabel();
        codigoOrgLabel = new javax.swing.JLabel();
        exentaVentaLabel = new javax.swing.JLabel();
        gravadaVentaLabel = new javax.swing.JLabel();
        ivaVentaLabel = new javax.swing.JLabel();
        totalExentaVentaLabel = new javax.swing.JLabel();
        totalGravadaVentaLabel = new javax.swing.JLabel();
        totalIvaVentaLabel = new javax.swing.JLabel();
        totVentaLabel = new javax.swing.JLabel();
        totIvaLabel = new javax.swing.JLabel();
        codigoSucursalLabel = new javax.swing.JLabel();
        codigoOrgLabel1 = new javax.swing.JLabel();
        codigoOrgLabel2 = new javax.swing.JLabel();
        diaLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numVtaC = new com.controles.JXTextFiled();
        diaField = new com.controles.JXTextFiled();
        documentoCBox = new com.controles.JXComboBox();
        NFormField = new com.controles.JXTextFiled();
        codOrg = new com.controles.JXTextFiled();
        nombreOrgField = new com.controles.JXTextFiled();
        numRegField = new com.controles.JXTextFiled();
        exentaVentaField = new com.controles.JXTextFiled();
        gravadaVentaField = new com.controles.JXTextFiled();
        ivaVentaField = new com.controles.JXTextFiled();
        totalExentaVentaField = new com.controles.JXTextFiled();
        totalGravadaVentaField = new com.controles.JXTextFiled();
        totalIvaVentaField = new com.controles.JXTextFiled();
        totVentaField = new com.controles.JXTextFiled();
        totIvaField = new com.controles.JXTextFiled();
        sucursalCBox = new com.controles.JXComboBox();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new com.controles.JXTable();
        txtDocumento = new com.controles.JXTextFiled();

        FormListener formListener = new FormListener();

        diaLabel.setText("Dia:");

        idDocLabel.setText("Documento:");

        NCompVentaLabel.setText("# Documento:");

        NFormLabel.setText("Formulario Unico:");

        codigoOrgLabel.setText("Cod. Cliente:");

        exentaVentaLabel.setText("Venta Exenta:");

        gravadaVentaLabel.setText("Venta Gravada:");

        ivaVentaLabel.setText("Débito Fiscal:");

        totalExentaVentaLabel.setText("Terceros Exentas:");

        totalGravadaVentaLabel.setText("Terceros Gravadas:");

        totalIvaVentaLabel.setText("Débito Terceros:");

        totVentaLabel.setText("Total Ventas:");

        totIvaLabel.setText("Impuesto percibido:");

        codigoSucursalLabel.setText("Sucursal:");

        codigoOrgLabel1.setText("Nombre Cliente:");

        codigoOrgLabel2.setText("No. Registro:");

        diaLabel1.setText("#:");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 11)); // NOI18N
        jLabel1.setText("Lista de ventas al consumidor final:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numVtaC}"), numVtaC, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numVtaC, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dia}"), diaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), diaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstDocumento, documentoCBox);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idDoc}"), documentoCBox, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), documentoCBox, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        NFormField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.NForm}"), NFormField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), NFormField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoOrg.codigoOrg}"), codOrg, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codOrg, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        codOrg.addActionListener(formListener);

        nombreOrgField.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoOrg.nombreOrg}"), nombreOrgField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nombreOrgField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        numRegField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numRegField.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoOrg.regIvaOrg}"), numRegField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numRegField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        exentaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.exentaVenta}"), exentaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), exentaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gravadaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.gravadaVenta}"), gravadaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), gravadaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ivaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ivaVenta}"), ivaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ivaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ivaVentaField.addFocusListener(formListener);

        totalExentaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totalExentaVenta}"), totalExentaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), totalExentaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        totalGravadaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totalGravadaVenta}"), totalGravadaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), totalGravadaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        totalIvaVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totalIvaVenta}"), totalIvaVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), totalIvaVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        totalIvaVentaField.addFocusListener(formListener);

        totVentaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totVenta}"), totVentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), totVentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        totVentaField.addFocusListener(formListener);

        totIvaField.setDecimal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.totIva}"), totIvaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), totIvaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstSucursal, sucursalCBox);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoSucursal}"), sucursalCBox, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), sucursalCBox, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVtaContribuyente, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numVtaC}"));
        columnBinding.setColumnName("#");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dia}"));
        columnBinding.setColumnName("Dia");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDoc}"));
        columnBinding.setColumnName("Documento");
        columnBinding.setColumnClass(com.entidades.Documento.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${NCompVenta}"));
        columnBinding.setColumnName("# Documento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${NForm}"));
        columnBinding.setColumnName("Formulario Unico");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoOrg}"));
        columnBinding.setColumnName("Código Cliente");
        columnBinding.setColumnClass(com.entidades.Organizacion.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoOrg.nombreOrg}"));
        columnBinding.setColumnName("Nombre Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoOrg.nitOrg}"));
        columnBinding.setColumnName("N.I.T.");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoOrg.regIvaOrg}"));
        columnBinding.setColumnName("# Registro");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${exentaVenta}"));
        columnBinding.setColumnName("Ventas Exentas");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gravadaVenta}"));
        columnBinding.setColumnName("Ventas Gravadas");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ivaVenta}"));
        columnBinding.setColumnName("Débito Fiscal");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalExentaVenta}"));
        columnBinding.setColumnName("Terceros Exentas");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalGravadaVenta}"));
        columnBinding.setColumnName("Terceros Gravadas");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalIvaVenta}"));
        columnBinding.setColumnName("Débito Terceros");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totIva}"));
        columnBinding.setColumnName("Impuesto Percibido");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totVenta}"));
        columnBinding.setColumnName("Total Ventas");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoSucursal}"));
        columnBinding.setColumnName("Sucursal");
        columnBinding.setColumnClass(com.entidades.Sucursal.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterTable.addMouseListener(formListener);
        masterScrollPane.setViewportView(masterTable);
        masterTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        masterTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        masterTable.getColumnModel().getColumn(2).setPreferredWidth(160);
        masterTable.getColumnModel().getColumn(3).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        masterTable.getColumnModel().getColumn(5).setPreferredWidth(180);
        masterTable.getColumnModel().getColumn(6).setPreferredWidth(250);
        masterTable.getColumnModel().getColumn(7).setPreferredWidth(150);
        masterTable.getColumnModel().getColumn(8).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(9).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(10).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(11).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(12).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(13).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(14).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(15).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(16).setPreferredWidth(120);
        masterTable.getColumnModel().getColumn(17).setPreferredWidth(120);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.NCompVenta}"), txtDocumento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtDocumento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(codigoOrgLabel)
                                            .addComponent(exentaVentaLabel)
                                            .addComponent(idDocLabel)
                                            .addComponent(diaLabel1)))
                                    .addComponent(totalExentaVentaLabel)
                                    .addComponent(totVentaLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(totVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(totalExentaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(codOrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(exentaVentaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(gravadaVentaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(codigoOrgLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(totalGravadaVentaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(totIvaLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(numVtaC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(diaLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(diaField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(totIvaField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                    .addComponent(gravadaVentaField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(totalGravadaVentaField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(totalIvaVentaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ivaVentaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(codigoSucursalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ivaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(totalIvaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sucursalCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nombreOrgField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(codigoOrgLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(documentoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(NCompVentaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(NFormLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NFormField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaLabel)
                    .addComponent(diaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaLabel1)
                    .addComponent(numVtaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDocLabel)
                    .addComponent(NCompVentaLabel)
                    .addComponent(NFormLabel)
                    .addComponent(NFormField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoOrgLabel)
                    .addComponent(codigoOrgLabel1)
                    .addComponent(nombreOrgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoOrgLabel2)
                    .addComponent(numRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exentaVentaLabel)
                    .addComponent(exentaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravadaVentaLabel)
                    .addComponent(gravadaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ivaVentaLabel)
                    .addComponent(ivaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalExentaVentaLabel)
                    .addComponent(totalExentaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalGravadaVentaLabel)
                    .addComponent(totalGravadaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalIvaVentaLabel)
                    .addComponent(totalIvaVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totVentaLabel)
                    .addComponent(totVentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totIvaLabel)
                    .addComponent(totIvaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoSucursalLabel)
                    .addComponent(sucursalCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == codOrg) {
                V_LibroVtaContribuyente.this.codOrgActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == ivaVentaField) {
                V_LibroVtaContribuyente.this.ivaVentaFieldFocusGained(evt);
            }
            else if (evt.getSource() == totalIvaVentaField) {
                V_LibroVtaContribuyente.this.totalIvaVentaFieldFocusGained(evt);
            }
            else if (evt.getSource() == totVentaField) {
                V_LibroVtaContribuyente.this.totVentaFieldFocusGained(evt);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == masterTable) {
                V_LibroVtaContribuyente.this.masterTableMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void codOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codOrgActionPerformed
        List<Organizacion> lstOrg = ServOrganizacion.getListado(1, codigoOrgField.getText());

        if (!lstOrg.isEmpty()) {
            nombreOrgField.setText(lstOrg.get(0).getNombreOrg());
            numRegField.setText(lstOrg.get(0).getRegIvaOrg());
            com.entidades.VentaContribuyente venta = lstVtaContribuyente.get(masterTable.convertRowIndexToModel(masterTable.getSelectedRow()));
            venta.setCodigoOrg(lstOrg.get(0));
        } else {
            JOptionPane.showMessageDialog(this, "Este cliente no esta registrado en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_codOrgActionPerformed

    private void totVentaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totVentaFieldFocusGained
        totVentaField.setText(String.valueOf(OperacionMatematica.getResultadoSumaFloat(exentaVentaField, gravadaVentaField, ivaVentaField)));
    }//GEN-LAST:event_totVentaFieldFocusGained

    private void ivaVentaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaVentaFieldFocusGained
        ivaVentaField.setText(String.valueOf(OperacionMatematica.getResultadoMultiplicacionFloat(gravadaVentaField, "0.".concat(System.getProperty("iva")))));
    }//GEN-LAST:event_ivaVentaFieldFocusGained

    private void totalIvaVentaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalIvaVentaFieldFocusGained
        totalIvaVentaField.setText(String.valueOf(OperacionMatematica.getResultadoMultiplicacionFloat(totalGravadaVentaField, "0.".concat(System.getProperty("iva")))));
    }//GEN-LAST:event_totalIvaVentaFieldFocusGained

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        //((VtnaProceso) this.getParent().getParent().getParent().getParent()).setEnableBotonBorrar(deleteButton.isEnabled());

        com.entidades.VentaContribuyente venta = lstVtaContribuyente.get(masterTable.convertRowIndexToModel(masterTable.getSelectedRow()));
        if (venta.getCodigoOrg() != null) {
            codOrg.setText(venta.getCodigoOrg().getCodigoOrg());
            nombreOrgField.setText(venta.getCodigoOrg().getNombreOrg());
            numRegField.setText(venta.getCodigoOrg().getRegIvaOrg());
        } else {
            limpiarOrg();
        }
    }//GEN-LAST:event_masterTableMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NCompVentaLabel;
    private com.controles.JXTextFiled NFormField;
    private javax.swing.JLabel NFormLabel;
    private com.controles.JXTextFiled codOrg;
    private com.controles.JXTextFiled codigoOrgField;
    private javax.swing.JLabel codigoOrgLabel;
    private javax.swing.JLabel codigoOrgLabel1;
    private javax.swing.JLabel codigoOrgLabel2;
    private javax.swing.JLabel codigoSucursalLabel;
    private com.controles.JXTextFiled diaField;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JLabel diaLabel1;
    private com.controles.JXComboBox documentoCBox;
    private javax.persistence.EntityManager entityManager;
    private com.controles.JXTextFiled exentaVentaField;
    private javax.swing.JLabel exentaVentaLabel;
    private com.controles.JXTextFiled gravadaVentaField;
    private javax.swing.JLabel gravadaVentaLabel;
    private javax.swing.JLabel idDocLabel;
    private com.controles.JXTextFiled ivaVentaField;
    private javax.swing.JLabel ivaVentaLabel;
    private javax.swing.JLabel jLabel1;
    private java.util.List<com.entidades.Documento> lstDocumento;
    private java.util.List<com.entidades.Sucursal> lstSucursal;
    private java.util.List<com.entidades.VentaContribuyente> lstVtaContribuyente;
    private javax.swing.JScrollPane masterScrollPane;
    private com.controles.JXTable masterTable;
    private com.controles.JXTextFiled nombreOrgField;
    private com.controles.JXTextFiled numRegField;
    private com.controles.JXTextFiled numVtaC;
    private com.controles.JXComboBox sucursalCBox;
    private com.controles.JXTextFiled totIvaField;
    private javax.swing.JLabel totIvaLabel;
    private com.controles.JXTextFiled totVentaField;
    private javax.swing.JLabel totVentaLabel;
    private com.controles.JXTextFiled totalExentaVentaField;
    private javax.swing.JLabel totalExentaVentaLabel;
    private com.controles.JXTextFiled totalGravadaVentaField;
    private javax.swing.JLabel totalGravadaVentaLabel;
    private com.controles.JXTextFiled totalIvaVentaField;
    private javax.swing.JLabel totalIvaVentaLabel;
    private com.controles.JXTextFiled txtDocumento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_LibroVtaContribuyente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_LibroVtaContribuyente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_LibroVtaContribuyente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_LibroVtaContribuyente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new V_LibroVtaContribuyente());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    private boolean existeResgitro() {
        return false;
    }

    private void limpiarOrg() {
        /*codigoOrgField.setText("");
         nombreOrgField.setText("");
         numRegField.setText("");*/
    }

    @Override
    public void guardar() {
        if (!existeResgitro()) {
            try {
                entityManager.getTransaction().commit();
                entityManager.getTransaction().begin();
            } catch (RollbackException rex) {
                rex.printStackTrace();
                entityManager.getTransaction().rollback();
                entityManager.getTransaction().begin();
                List<com.entidades.VentaContribuyente> merged = new ArrayList<com.entidades.VentaContribuyente>(lstVtaContribuyente.size());
                for (com.entidades.VentaContribuyente v : lstVtaContribuyente) {
                    merged.add(entityManager.merge(v));
                }
                lstVtaContribuyente.clear();
                lstVtaContribuyente.addAll(merged);
            } finally {
            }
        }
    }

    @Override
    public void eliminar() {
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar este registro?",
                "Operación de eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            int[] selected = masterTable.getSelectedRows();
            List<com.entidades.VentaContribuyente> toRemove = new ArrayList<com.entidades.VentaContribuyente>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                com.entidades.VentaContribuyente v = lstVtaContribuyente.get(masterTable.convertRowIndexToModel(selected[idx]));
                v.setEliminado(true);
                toRemove.add(v);

                if (v.getIdVenta() != null);
                guardar();
            }
            lstVtaContribuyente.removeAll(toRemove);
            Integer id = 1;
            for (VentaContribuyente ventaContribuyente : lstVtaContribuyente) {
                ventaContribuyente.setNumVtaC(id);
                id = id + 1;
            }
            
            guardar();
        }

        limpiarOrg();
    }

    @Override
    public void actualizar() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.List<VentaContribuyente> data = ServVtaContribuyente.getListado();
        for (VentaContribuyente entity : data) {
            entityManager.refresh(entity);
        }
        lstVtaContribuyente.clear();
        lstVtaContribuyente.addAll(data);
    }

    @Override
    public void nuevo() {
        limpiarOrg();

        com.entidades.VentaContribuyente vNew = new com.entidades.VentaContribuyente();
        int num;
        if (masterTable.getRowCount() != 0) {
            num = lstVtaContribuyente.get(masterTable.getRowCount() - 1).getNumVtaC() + 1;
        } else {
            num = 1;
        }

        vNew.setNumVtaC(num);
        vNew.setMesAnhoVtaC(Fechas.getNumeroMes(System.getProperty("mes")).concat(System.getProperty("anho")));
        vNew.setIdUsuario(AccesoAVtaPadre.getUsuario());
        vNew.setCodigoSucursal((Sucursal) sucursalCBox.getSelectedItem());
        vNew.setCodigoOrg(entityManager.find(Organizacion.class, ""));
        vNew.setIdDoc(entityManager.find(Documento.class, -1));
        vNew.setCsvVtaC(true);
        vNew.setEliminado(false);

        entityManager.persist(vNew);
        lstVtaContribuyente.add(vNew);
        int row = lstVtaContribuyente.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        masterTable.requestFocus();
        masterTable.changeSelection(row, 1, false, false);
    }

    @Override
    public void suma() {
        VtnaSuma sum = new VtnaSuma(AccesoAVtaPadre.vtaPadre, true);

        sum.add(new V_SumVtaContribuyente());
        sum.pack();
        sum.setLocationRelativeTo(this);
        sum.setVisible(true);

        System.gc();
    }
    private Boolean enableEliminar = false;

    @Override
    public void setEnabledEliminar(Boolean eliminar) {
        this.enableEliminar = eliminar;
    }

    @Override
    public Boolean getEnabledEliminar() {
        return enableEliminar;
    }
}